### ISSUE TITLE
add 3 VRFs (blue, red, yellow)

### ISSUE THREAD

**Issue by glimchb** [opiproject/opi-evpn-bridge#8]
see https://github.com/opiproject/opi-evpn-bridge/blob/2d7ea90f6a281affe82f74b0879a1a5c15fca77c/conf/example.conf

**Comment by venkatmahalingam** [comment]
https://github.com/opiproject/opi-evpn-bridge/pull/18

**Comment by venkatmahalingam** [comment]
The code changes are being reviewed now.
